[theme]
primaryColor = "#9faddd"
backgroundColor = "#080a13"
secondaryBackgroundColor = "#192552"
textColor = "#f1f8fc"
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap"